./resources/automatic-metrics.sh sql-rq2-base-gpt4o-paper sql
./resources/automatic-metrics.sh sql-rq2-example-gpt4o-paper sql
./resources/automatic-metrics.sh sql-rq3-alg-base-gpt4o-paper sql
./resources/automatic-metrics.sh sql-rq3-alg-example-gpt4o-paper sql
./resources/automatic-metrics.sh sql-rq3-dec-base-gpt4o-paper sql
./resources/automatic-metrics.sh sql-rq3-dec-example-gpt4o-paper sql
./resources/automatic-metrics.sh demand-rq4-base-gpt4o-paper demand
./resources/automatic-metrics.sh demand-rq4-example-gpt4o-paper demand
./resources/automatic-metrics.sh demand-rq5-base-gpt4o-paper demand
./resources/automatic-metrics.sh demand-rq5-example-gpt4o-paper demand